import {test} from 'node:test';
import assert from 'node:assert/strict';
import {act,createSession,estimate,approvalValid,verifySession,scenarios} from '../../src/features/worldos/engine.ts';
async function prepared(){let s=await createSession();for(const key of scenarios[0].requirements)s=await act(s,'reviewer',{type:'evidence',key,value:true});return s;}
test('three comparable fixed-horizon costs with disclosed sensitivity',async()=>{const s=await createSession();assert.deepEqual(scenarios.map(x=>estimate(s.model,x.id).total),[3030,6270,5250]);for(const x of scenarios){const e=estimate(s.model,x.id);assert.equal(e.acuteDays+e.postDays,7);assert.equal(e.low,Math.round(e.total*.8));}});
test('time passing does not fill evidence gaps',async()=>{const s=await createSession();assert.deepEqual(estimate(s.model,'homeTomorrow').missing,estimate(s.model,'homeLater').missing);});
test('missing evidence prevents approval and records the hold',async()=>{let s=await createSession();s=await act(s,'reviewer',{type:'approve'});assert.equal(s.model.approval,null);assert.equal(s.events.at(-1).action,'APPROVAL_HELD');assert.ok(await verifySession(s));});
test('AI cannot approve or attest evidence',async()=>{let s=await prepared();s=await act(s,'agent',{type:'approve'});assert.equal(s.events.at(-1).action,'APPROVAL_DENIED');s=await act(s,'agent',{type:'evidence',key:'coverage',value:false});assert.equal(s.events.at(-1).action,'EVIDENCE_DENIED');assert.equal(s.model.evidence.coverage,true);});
test('human approval permits one simulated execution only',async()=>{let s=await prepared();s=await act(s,'reviewer',{type:'approve'});assert.ok(approvalValid(s.model));s=await act(s,'reviewer',{type:'execute'});assert.ok(s.model.executed);s=await act(s,'reviewer',{type:'execute'});assert.equal(s.events.at(-1).action,'EXECUTION_DENIED');assert.ok(await verifySession(s));});
test('AI cannot execute a human-approved plan',async()=>{let s=await prepared();s=await act(s,'reviewer',{type:'approve'});s=await act(s,'agent',{type:'execute'});assert.equal(s.model.executed,false);});
test('scenario, evidence and cost changes each revoke approval',async()=>{for(const action of [{type:'select',value:'homeLater'},{type:'evidence',key:'coverage',value:false},{type:'assumptions',value:{acuteDaily:2000,homeDaily:180,facilityDaily:550,transport:150}}]){let s=await prepared();s=await act(s,'reviewer',{type:'approve'});s=await act(s,'reviewer',action);assert.equal(s.model.approval,null);assert.ok(!approvalValid(s.model));}});
test('expired approval cannot execute',async()=>{let s=await prepared();s=await act(s,'reviewer',{type:'approve'},1000);s=await act(s,'reviewer',{type:'execute'},1000+900001);assert.equal(s.events.at(-1).action,'EXECUTION_DENIED');});
test('trail survives JSON serialization and detects event or snapshot edits',async()=>{let s=await prepared();s=await act(s,'reviewer',{type:'compare'});assert.ok(await verifySession(JSON.parse(JSON.stringify(s))));const tamper=structuredClone(s);tamper.model.version++;assert.equal(await verifySession(tamper),false);const event=structuredClone(s);event.events[0].result='Changed';assert.equal(await verifySession(event),false);});
test('invalid cost input rejected',async()=>{const s=await createSession();await assert.rejects(()=>act(s,'reviewer',{type:'assumptions',value:{acuteDaily:-10,homeDaily:180,facilityDaily:550,transport:150}}));});
