import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import Footer from "../components/Footer";

export default function FlyerPage(){
 const programs=["CJR-X Recovery-in-a-Box™","ACCESS Care-in-a-Box™","PIN-in-a-Box™","Wound Care-in-a-Box™","Precision Recovery / LTACH OS™","Senior Care-in-a-Box™"];
 return <div className="bg-slate-100 py-10 text-slate-950"><div className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] bg-white shadow-2xl">
  <section className="bg-gradient-to-br from-slate-950 via-blue-950 to-cyan-800 px-8 py-14 text-white md:px-14"><p className="font-black uppercase tracking-[.2em] text-cyan-300">Absolute Health Group™</p><h1 className="mt-3 text-5xl font-black md:text-7xl">Care-in-a-Box™</h1><p className="mt-3 text-2xl font-bold text-cyan-200">Deploy. Connect. Care. Measure. Prove. Scale.</p><p className="mt-7 max-w-3xl text-xl leading-8 text-blue-100">Bring specialty care into your organization without building the specialty infrastructure yourself.</p></section>
  <section className="grid gap-8 px-8 py-12 md:grid-cols-2 md:px-14"><div><p className="text-sm font-black tracking-[.18em] text-blue-700">WHAT YOU DEPLOY</p><h2 className="mt-3 text-3xl font-black">One platform. Multiple care programs.</h2><div className="mt-6 space-y-3">{programs.map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-cyan-700"/><span className="font-bold">{x}</span></div>)}</div></div><div className="rounded-3xl bg-slate-50 p-7"><p className="text-sm font-black tracking-[.18em] text-blue-700">WHAT YOU OPERATE</p><h3 className="mt-3 text-3xl font-black">GitHealth™</h3><p className="mt-4 leading-7 text-slate-600">Opportunities · Populations · Care Programs · Workflows · Evidence · Outcomes · Economics · Reports</p><div className="mt-7 border-t border-slate-200 pt-6"><div className="font-black">Medical Navigator AI™</div><p className="mt-2 text-sm text-slate-600">Navigates the work while preserving appropriate human authority.</p><div className="mt-5 font-black">AION™</div><p className="mt-2 text-sm text-slate-600">Governed intelligence and authority underneath the operating surface.</p></div></div></section>
  <section className="bg-blue-50 px-8 py-10 md:px-14"><h3 className="text-2xl font-black">Work → Evidence → Outcome → Economics</h3><p className="mt-3 max-w-3xl text-slate-600">Workflow Units™ define completed governed work. Prove™ establishes evidence and provenance. ZScore™ benchmarks performance. Economics™ measures Cost-to-Goal™, contribution and ROI.</p></section>
  <section className="bg-slate-950 px-8 py-12 text-white md:px-14"><h2 className="text-4xl font-black">Tell us the care problem.<br/>We deploy the box.</h2><p className="mt-4 max-w-2xl text-blue-100">Start with an Opportunity Assessment to define the population, workflow, evidence requirements, operating model and measurable goal.</p><Link to="/contact?buyer=Care-in-a-Box" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-6 py-3 font-black text-blue-950">Get Started <ArrowRight className="h-4 w-4"/></Link></section>
 </div><Footer/></div>
}
