import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, Check, ChevronRight, Clock3, Download, FileCheck2, FlaskConical, GitBranch, LockKeyhole, Play, RefreshCw, ShieldCheck } from 'lucide-react';
import { act, approvalValid, createSession, episodeId, estimate, evidenceLabels, policy, scenarios, verifySession, type Action, type Assumptions, type DemoActor, type EvidenceKey, type Session } from '../features/worldos/engine';
import './worldos.css';
const storageKey='githealth-worldos-synthetic-v1';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function WorldOSPage(){
 const [session,setSession]=useState<Session|null>(null);const [actor,setActor]=useState<DemoActor>('reviewer');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [integrity,setIntegrity]=useState('Checking');const [clock,setClock]=useState(Date.now());const locked=useRef(false);
 useEffect(()=>{let mounted=true;(async()=>{let next:Session;let warning='';try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw);if(await verifySession(parsed))next=parsed;else{next=await createSession();warning='Saved demo failed integrity verification. A new session was started.';}}else next=await createSession();}catch{next=await createSession();warning='Browser storage unavailable; this session may not survive refresh.';}if(mounted){setSession(next);setIntegrity('Verified');setNotice(warning);}})();const t=setInterval(()=>setClock(Date.now()),1000);return()=>{mounted=false;clearInterval(t);};},[]);
 async function dispatch(action:Action){if(!session||locked.current)return;locked.current=true;setBusy(true);try{const next=await act(session,actor,action);setSession(next);setIntegrity(await verifySession(next)?'Verified':'Failed');setNotice(next.events[next.events.length-1]!.result);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{setNotice('Action recorded in memory. Browser storage failed; export your trail before leaving.');}}catch(e){setNotice(e instanceof Error?e.message:'Action failed');}finally{locked.current=false;setBusy(false);}}
 async function reset(){if(!window.confirm('Start a new synthetic session? Export the current trail first if you want to keep it.'))return;const next=await createSession();setSession(next);setIntegrity('Verified');setNotice('New synthetic session started.');try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{setNotice('New session started in memory; browser storage is unavailable.');}}
 async function download(){if(!session)return;const valid=await verifySession(session);setIntegrity(valid?'Verified':'Failed');if(!valid){setNotice('Export blocked: audit integrity verification failed.');return;}const bundle={...session,exportedAt:new Date().toISOString(),episodeId,limitations:'Synthetic browser demonstration. Demo roles are not authenticated identities. Hashes are not externally anchored. No actual discharge, payment or clinical outcome.',scenarioEstimates:scenarios.map(s=>({id:s.id,...estimate(session.model,s.id)}))};const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='githealth-worldos-synthetic-proof.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!session)return <div className="wo"><p className="wo-loading">Loading synthetic episode…</p></div>;
 const m=session.model;const selected=scenarios.find(s=>s.id===m.selected)!;const current=estimate(m,m.selected);const ready=approvalValid(m,clock);const confirmed=Object.values(m.evidence).filter(Boolean).length;
 return <div className="wo"><div className="wo-shell">
  <div className="wo-top"><div className="wo-brand"><span className="wo-mark"><GitBranch size={22}/></span><div>GitHealth <b>WorldOS</b><small>EPISODE COMMAND CENTER</small></div></div><div className="wo-top-actions"><span className="wo-badge"><FlaskConical size={13}/> SYNTHETIC SANDBOX</span><button onClick={download} disabled={busy}><Download size={15}/> Export trail</button><button onClick={reset} disabled={busy} aria-label="Reset demo"><RefreshCw size={15}/></button></div></div>
  <div className="wo-hero"><div><div className="wo-eyebrow">CARE-IN-A-BOX / EPISODE TWIN</div><h1>See the options.<br/><span>Govern the next step.</span></h1><p>One episode. Three possible transitions. Every decision leaves a trace.</p></div><div className="wo-mode"><span className="wo-dot"/> Interactive demonstration<small>Deterministic scenarios · simulated operations<br/>No live EHR, payer or patient connection</small></div></div>
  <div className="wo-metrics"><div><small>EPISODE</small><strong>{episodeId}</strong><span>Post-acute transition</span></div><div><small>EVIDENCE CONFIRMED</small><strong>{confirmed}<em> / 6</em></strong><span>{6-confirmed} synthetic records missing</span></div><div><small>AUTHORITY STATE</small><strong className="wo-state">{m.executed?'Simulated handoff':ready?'Approved · demo':'Human review'}</strong><span>Version {m.version} · {policy}</span></div><div><small>PROOF TRAIL</small><strong>{session.events.length}<em> events</em></strong><span className="wo-teal">{integrity} local hash chain</span></div></div>
  <div className="wo-workspace"><aside className="wo-left"><section className="wo-panel"><div className="wo-section-label">01 / EPISODE CONTEXT</div><h2>Transition readiness</h2><div className="wo-avatar">S1</div><h3>Synthetic patient 001</h3><p>Illustrative adult recovering from an acute admission. Follow-up and receiving-team handoff require review.</p><dl><div><dt>Current setting</dt><dd>Acute hospital</dd></div><div><dt>Decision window</dt><dd>D+1 to D+3</dd></div><div><dt>Clinical prediction</dt><dd>Not modeled</dd></div></dl><div className="wo-network"><div><Activity size={16}/> Hospital</div><ChevronRight size={16}/><div><GitBranch size={16}/> Home / facility</div></div><p className="wo-fine">All identities, records, readiness states and costs are invented for this demonstration.</p></section>
  <section className="wo-panel"><div className="wo-section-label">DETERMINISTIC WORKFLOW ROLES</div>{[['Intake','Synthetic context loaded'],['Evidence','Required-record checks'],['PolicyPulse','Demo policy rules only'],['Scenario','Resource arithmetic'],['AION','Human review gate'],['Proof','Local event chain']].map(([name,desc])=><div className="wo-agent" key={name}><span className="wo-dot"/><div><b>{name}</b><small>{desc}</small></div></div>)}<p className="wo-fine">Scripted roles; no autonomous or model-based agents are running.</p></section></aside>
  <div className="wo-center"><section className="wo-panel"><div className="wo-section-head"><div><div className="wo-section-label">02 / SCENARIO LAB</div><h2>What if the transition changes?</h2></div><button onClick={()=>dispatch({type:'compare'})} disabled={busy}><Play size={14}/> Compare</button></div><p>Compare a fixed seven-day resource window. A later date does not automatically resolve missing evidence.</p><div className="wo-scenarios">{scenarios.map((s,i)=>{const e=estimate(m,s.id);return <button className={'wo-scenario '+(m.selected===s.id?'selected':'')} aria-pressed={m.selected===s.id} key={s.id} onClick={()=>dispatch({type:'select',value:s.id})} disabled={busy}><div className="wo-scenario-number">0{i+1}<span>{m.selected===s.id?'SELECTED':'EXPLORE'}</span></div><h3>{s.name}</h3><div className="wo-timing"><Clock3 size={13}/>{s.timing}</div><strong>{money(e.total)}</strong><small>Illustrative resource cost</small><div className="wo-range">{money(e.low)}–{money(e.high)}<br/>±20% sensitivity assumption</div><div className={'wo-readiness '+(e.missing.length?'':'clear')}>{e.missing.length?`${e.missing.length} evidence gaps`:'Evidence ready for review'}</div></button>;})}</div><div className="wo-cost-note">{current.acuteDays} acute days + {current.postDays} {selected.setting.toLowerCase()} days + transport. Planning costs only; no reimbursement, savings or clinical benefit is predicted.</div>
   <details className="wo-assumptions"><summary>Adjust resource assumptions <span>USD · illustrative</span></summary><div className="wo-input-grid">{([['acuteDaily','Acute care / day'],['homeDaily','Home services / day'],['facilityDaily','Facility care / day'],['transport','Transport / episode']] as [keyof Assumptions,string][]).map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="10000" step="10" value={m.assumptions[key]} disabled={busy} onChange={e=>{if(e.target.value!=='')dispatch({type:'assumptions',value:{...m.assumptions,[key]:Number(e.target.value)}});}}/></label>)}</div><p className="wo-fine">Editing any assumption creates a new version and invalidates approval.</p></details></section>
   <section className="wo-panel"><div className="wo-section-label">03 / EVIDENCE WORKSPACE</div><h2>Resolve the missing pieces</h2><p>Toggle synthetic confirmations as the demo reviewer. This represents evidence arrival, not actual clinical validation.</p><div className="wo-evidence">{(Object.keys(evidenceLabels) as EvidenceKey[]).map(key=><label key={key} className={m.evidence[key]?'confirmed':''}><input type="checkbox" checked={m.evidence[key]} disabled={busy||actor!=='reviewer'} onChange={e=>dispatch({type:'evidence',key,value:e.target.checked})}/><div><b>{evidenceLabels[key]}</b><small>synthetic://{episodeId}/{key} · {m.evidence[key]?'confirmed':'missing'}</small></div><span>{selected.requirements.includes(key)?'Required':'Other pathway'}</span></label>)}</div></section>
   <section className="wo-panel"><div className="wo-section-label">PROPOSED HANDOFF PLAN</div><h2>{selected.name}</h2>{selected.tasks.map((t,i)=><div className="wo-task" key={t}><span>{i+1}</span>{t}<small>{m.executed?'Simulated record created':'Proposed only'}</small></div>)}<p className="wo-fine">Coordination outline only. A clinician-authored care plan and actual orders are outside this prototype.</p></section></div>
  <aside className="wo-right"><section className="wo-panel wo-authority"><div className="wo-section-label">04 / AION AUTHORITY</div><h2><ShieldCheck size={20}/> Review before action</h2><label className="wo-role">Demo role<select value={actor} onChange={e=>setActor(e.target.value as DemoActor)} disabled={busy}><option value="reviewer">Human reviewer · simulated</option><option value="agent">AI agent · simulated</option></select></label><p className="wo-fine">Role selection is a demonstration control, not authentication.</p><div className="wo-gates">{[['G0–1','Identity & purpose','Synthetic sandbox only',true],['G2','Evidence',current.missing.length?`${current.missing.length} requirements missing`:'Required records confirmed',!current.missing.length],['G3','Policy',policy+' · fictional rules',true],['G4','Human approval',m.executed?'Approval consumed by handoff':ready?'Current version approved':'Approval required',ready||m.executed],['G5','Execution',m.executed?'Simulated handoff recorded':'Held until valid approval',m.executed],['G6','Proof',`${session.events.length} chained events`,integrity==='Verified']].map(([id,name,desc,ok])=><div className="wo-gate" key={String(id)}><span className={ok?'pass':''}>{ok?<Check size={12}/>:<LockKeyhole size={12}/>}</span><div><b>{id} · {name}</b><small>{desc}</small></div></div>)}</div><button className="wo-primary" onClick={()=>dispatch({type:'approve'})} disabled={busy}>Review & approve demo plan <ArrowRight size={14}/></button><button className="wo-execute" onClick={()=>dispatch({type:'execute'})} disabled={busy}>Simulate handoff</button><button className="wo-hold" onClick={()=>dispatch({type:'hold'})} disabled={busy}>Hold for review</button><p className="wo-fine">Approval expires after 15 minutes. Scenario, evidence or cost changes revoke it. Blocked attempts are recorded.</p></section><div className="wo-notice" role="status" aria-live="polite">{notice||'Select a scenario, confirm its required evidence, then review the proposed plan.'}</div></aside></div>
  <section className="wo-panel wo-trail"><div className="wo-section-head"><div><div className="wo-section-label">05 / AUTHORIZATION & PROOF TRAIL</div><h2><FileCheck2 size={20}/> Every step, attributable in the demo</h2></div><span className="wo-badge">SHA-256 · {integrity}</span></div><div className="wo-events">{[...session.events].reverse().map(e=><details key={e.sequence}><summary><span className="wo-seq">{String(e.sequence).padStart(2,'0')}</span><b>{e.action.replace(/_/g,' ')}</b><span>{e.actor}</span><time>{new Date(e.time).toLocaleTimeString()}</time></summary><p>{e.result}</p><code>Hash: {e.hash}<br/>Previous: {e.previousHash}</code><p className="wo-fine">Episode version {e.snapshot.version} · Policy {e.policy}</p></details>)}</div><p className="wo-fine">Stored in this browser. Hashes detect ordinary edits; they are not signed, externally anchored, or production-grade proof. Export preserves the full input snapshots and event chain.</p></section>
 <footer className="wo-footer">GitHealth WorldOS <span>Healthcare simulation + command + authority</span><small>Exploratory prototype · No autonomous clinical decisions</small></footer>
 </div></div>;
}
