import { Bot, Braces, CircleHelp } from 'lucide-react';
import { evidenceLabels, type AuditEvent, type Model } from './engine';
const names={gather_evidence:'Gather missing evidence',resolve_conflict:'Resolve conflicting evidence',request_human_review:'Request human review',inspect_execution_record:'Inspect the execution record'};
export default function DecisionAgentPanel({model,events,busy,onRun}:{model:Model;events:AuditEvent[];busy:boolean;onRun:()=>void}){
 const record=[...events].reverse().find(e=>e.agentDecision);
 const decision=record?.agentDecision;
 const stale=!!decision&&(decision.episode_version!==model.version||record.snapshot.executed!==model.executed);
 return <section id="episode-agent" className="wo-panel wo-decision"><div className="wo-section-head"><div><div className="wo-section-label">EPISODE DECISION AGENT / V0.1</div><h2><Bot size={20}/> What needs to happen next?</h2></div><button className="wo-agent-run" onClick={onRun} disabled={busy}>Run decision agent</button></div><p>Typed questions. Structured answers. Explicit unknowns. The agent checks the selected episode pathway and proposes the next workflow step.</p>
 <div className="wo-agent-provider">LOCAL RULES ENGINE <span>No Jev API connected</span></div>
 {!decision?<div className="wo-decision-empty"><Braces size={24}/><p>Select a scenario, then run the agent to inspect its typed decision.</p></div>:<><div role="status" className={stale?'wo-decision-stale':'wo-decision-result'}><small>{stale?'STALE RESULT — RUN AGAIN':'PROPOSED NEXT STEP'}</small><strong>{names[decision.choice.value]}</strong><span>Episode v{decision.episode_version} · {decision.scenario_id}</span></div><div className="wo-decision-grid"><div><small>EVIDENCE COMPLETENESS</small><strong>{decision.score.confirmed} / {decision.score.required}</strong><span>{Math.round(decision.score.value*100)}% of required records confirmed</span></div><div><small>MODEL CONFIDENCE</small><strong>Not estimated</strong><span>No calibrated model connected</span></div></div><div className="wo-agent-assertions">{decision.assertions.map(a=><div key={a.key}><span>{evidenceLabels[a.key]}</span><b className={a.value==='confirmed'?'confirmed':''}>{a.value.toUpperCase()}</b></div>)}</div><div className="wo-agent-limits"><CircleHelp size={15}/><span>Completeness is a record count, not a probability of safe discharge. Clinical readiness is not assessed. Human approval is always required.</span></div><details className="wo-agent-json"><summary>Inspect typed output</summary><pre>{JSON.stringify(decision,null,2)}</pre></details></>}
 <p className="wo-fine">Each run is schema-validated and attached to the local audit trail. The agent cannot approve or execute a care action.</p></section>;
}
